username=Karthik
validUsername=Karthik
validEmail=valid@test.com
invalidEmail=invalid@test.com
registerEmail=temp@test.com
registerName=Karthik
password=karthik
baseUrl=https://automationexercise.com
apiBaseUrl=https://automationexercise.com
browser=firefox
schemaPath=schemas/productsSchema.json
reportsPath=../reports/automation-report.html